services:
  bff:
    build: .
    ports:
      - "8085:8080"
    environment:
      POINT_SERVICE_URL: http://point-service:8080
      USER_SERVICE_URL: http://user-service:8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
