spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: user-service
server:
  port: 8081
